### ISSUE TITLE
Slider does not show up

### ISSUE THREAD

**Issue by fzenoni** [dreamRs/resizer#2]
Hello, thank you for this nice package.

I am experiencing an issue on Ubuntu 18.04 with both Firefox and Chrome, where the sliders to select height and width do not appear. The shortcuts work properly though. Would you have any suggestions ?
![resizer](https://user-images.githubusercontent.com/6040873/114990715-17b73680-9e99-11eb-8ff5-08e21a97242c.png)

**Comment by pvictor** [comment]
Thanks for reporting this bug, it should work now!

Victor

**Comment by fzenoni** [comment]
Amazing! Merci beaucoup !

**Comment by dfdeagle47** [comment]
For reference: fixed via https://github.com/dreamRs/resizer/commit/95c2ae2a5d70125c96a064cdeff30b7cb2bde306.

(I imagine this issue can be closed as well?)

**Comment by pvictor** [comment]
yes, thanks
